### ISSUE TITLE
Notarized height is higher than my height

### ISSUE THREAD

**Issue by TheTrunk** [MyHush/hush3#10]
When notarized height is higher than my last tip following error occurs preventing syncing with blockchain - resulting in getting banned from peers.

```
2019-04-21 10:04:25 ERROR: ActivateBestChainStep(): pindexFork->GetHeight().1 is < notarizedht 2130, so ignore it
2019-04-21 10:04:25 ERROR: ProcessNewBlock: ActivateBestChain failed
```

I suppose this is a result of some local corruption of data. It is happening to me quite often actually and the only solution was to delete the entire HUSH3 folder (including wallet.dat file).
#9

**Comment by leto** [comment]
@TheTrunk this should be fixed in the latest `dev` branch

**Comment by leto** [comment]
This is resolved
