### ISSUE TITLE
Building now requires xz

### ISSUE THREAD

**Issue by EvilRedHorse** [MyHush/hush3#101]
###Description:
hush3 build fails due to missing `xz` program - in a previously working build env.

###Solution for Fedora:
`sudo dnf -y install xz`

###Error:
`/home/hush3-3.3.2/depends/sources/ccache-3.7.7.tar.xz: OK
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
make: *** [funcs.mk:259: /home/hush3-3.3.2/depends/work/build/x86_64-pc-linux-gnu/native_ccache/3.7.7-28b18e56782/.stamp_extracted] Error 2
make: Leaving directory '/home/hush3-3.3.2/depends' `

**Comment by leto** [comment]
@EvilRedHorse thanks for this bug report! If you join our Discord at https://myhush.org/discord/ I can send you a tip

**Comment by leto** [comment]
@EvilRedHorse thanks for reporting, this is now fixed on dev. I will leave this open until it's fixed on master

**Comment by leto** [comment]
Fixed in 3.4.0
