### ISSUE TITLE
keypool refill unresponsivness, freeze

### ISSUE THREAD

**Issue by TheTrunk** [MyHush/hush3#11]
Running keepoolrefill command sometimes results in unresponsivnes, freeze. Mostly after performing some actiong with addresses (such as generating, sending)

**Comment by leto** [comment]
@TheTrunk any other data on this? That RPC command has not been modified at all from KMD and I am pretty sure ZEC has not modified from BTC upstream

**Comment by leto** [comment]
Please re-open if this bug still happens, I believe it only happened in very old code
