### ISSUE TITLE
Komodo Notary Season 4

### ISSUE THREAD

**Issue by tonymorony** [MyHush/hush3#114]
Dear @leto ,

We are pleased to release the new Komodo 0.6.0 version, called "Draconic Serpent," which will hardfork the Komodo network to the 4th dPoW season on June 14th, 2020.
Exact height/timestamp can be found here ( approx. June 14th, 2020 03:00:00 PM UTC) : https://github.com/KomodoPlatform/komodo/blob/master/src/komodo_globals.h#L48

List of the third-party pubkeys for this season can be found here: https://github.com/KomodoPlatform/dPoW/blob/s4/iguana/3rd_party#L15

Please update your codebase accordingly for dPoW consensus protection and update infrastructure daemons/exchanges. We recommend contacting exchanges you listed on to pause all wallet-operations (withdraws & deposits) from June 13th, 12:00 PM UTC until June 15th 12:00 PM UTC in order to ensure a smooth network transition. 

Have a great day and stay safe!

**Comment by leto** [comment]
@tonymorony thank you so much for reaching out, thank you

**Comment by leto** [comment]
@tonymorony thanks for all your help with this :tada:

**Comment by tonymorony** [comment]
I wish Hush devs and community a wonderful and productive season 4! @leto
