### ISSUE TITLE
WavesDex Integration 

### ISSUE THREAD

**Issue by khara2** [MyHush/hush3#29]
I will provide the neccecary info and files to integrate into WavesDex

Link: https://github.com/jansenmarc/WavesGatewayFramework

Example: A guide on how LTC was integrated into WavesDex. I will upload the files. https://github.com/jansenmarc/WavesGatewayLTCExample

[WavesGatewayLTCExample-master.zip](https://github.com/MyHush/hush3/files/3536719/WavesGatewayLTCExample-master.zip)

**Comment by leto** [comment]
@khara2 thanks for this info, will research :+1:

**Comment by leto** [comment]
Not pursuing this
