### ISSUE TITLE
Fix -clientname

### ISSUE THREAD

**Issue by leto** [MyHush/hush3#3]
This argument does not seem to take effect, and the default is always used.

Send this upstream to KMD, too

**Comment by leto** [comment]
Bounty: 25 HUSH

**Comment by AstrohackerX** [comment]
Done. Tested. https://github.com/AstrohackerX/komodo-fork/commit/be9746907559b59ead1fcb7f6a0df737a01c205d
![2](https://user-images.githubusercontent.com/49689096/56507166-26c4b180-6529-11e9-8bb2-87065e772136.jpg)

**Comment by leto** [comment]
@AstrohackerX can you send a PR with this fix?

**Comment by leto** [comment]
I fixed this
