### ISSUE TITLE
3.2 not working

### ISSUE THREAD

**Issue by laakie** [MyHush/hush3#39]
komodod: main.cpp:4443: void PruneBlockIndexCandidates(): Assertion `!setBlockIndexCandidates.empty()' failed.

On start.
When reindex it don't get further then block 253, banns all nodes for misbehaving.

V3.1.1 works flawless though,

**Comment by leto** [comment]
@laakie thank you for reporting this! We are actively working on an updated release and will update this issue when it's ready :+1:

**Comment by leto** [comment]
@laakie these issues have been fixed in 3.2.1 : https://github.com/MyHush/hush3/releases/tag/v3.2.1

Thanks again for your bug report! :+1:

**Comment by laakie** [comment]
@leto Works like a charm now.
Thank you! 
Great job !
