### ISSUE TITLE
Debian package install fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by dbongo** [MyHush/hush3#40]
### Machine specs:
- OS name + version: 
  ```
  Ubuntu 16.04.6
  ```
- Linux kernel version (uname -a):
  ```
  Linux ubuntu-xenial 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
  ```
- Compiler version: 
  ```
  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)
  ```
- Platform: 
  ```
  Virtualbox
  - CPU: 1
  - RAM: 4GB
  ```

### Dpkg output:
```sh
$ vagrant ssh
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-166-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage


0 packages can be updated.
0 updates are security updates.

New release '18.04.3 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

vagrant@ubuntu-xenial:~$ cd hush3
vagrant@ubuntu-xenial:~/hush3$ sudo dpkg -i hush-3.2.1-amd64.deb

Selecting previously unselected package hush.
(Reading database ... 61769 files and directories currently installed.)
Preparing to unpack hush-3.2.1-amd64.deb ...
Unpacking hush (3.2.1) ...

dpkg: dependency problems prevent configuration of hush:

  hush depends on libc6 (>= 2.29); however:
    Version of libc6:amd64 on system is 2.23-0ubuntu11.

  hush depends on libstdc++6 (>= 7); however:
    Version of libstdc++6:amd64 on system is 5.4.0-6ubuntu1~16.04.I 11.
```
Coincidently ran into an issue similar to this at work a few months ago. We had to update the kernel to the latest available version without doing a major upgrade but it resolved the dependency issues.

**Comment by leto** [comment]
@dbongo thanks for this report. I think we can either bundle those libs with the binaries, or compile things statically to prevent this error

**Comment by leto** [comment]
@dbongo the core reason was that I was generating the .deb on Ubuntu 19 without proper static libraries configured. We will be generating new debs for a new release soon, and once we can confirm they work on Ubuntu 16.04, we will close this issue. Thanks again for your bug report.

**Comment by leto** [comment]
@dbongo our new Debian package is generated on Ubuntu 16.04, so it should hopefully work! Please open a new Github Issue if you run into any issues with our new deb

**Comment by dbongo** [comment]
@leto will do. Thanks again for getting back to me on this!
