### ISSUE TITLE
Libsodium 1.0.15 is old and unsupported

### ISSUE THREAD

**Issue by leto** [MyHush/hush3#44]
libsodium just moved the URL of the binary we download, breaking our build system and most likely almost all Zcash coin build systems.

  * Hush should not depend on unsupported libsodium
  * Hush should protect itself against the URL of libsodium changing again (this is the 2nd time it's changed)

```
--- a/depends/packages/libsodium.mk
+++ b/depends/packages/libsodium.mk
@@ -1,6 +1,6 @@
 package=libsodium
 $(package)_version=1.0.15
-$(package)_download_path=https://download.libsodium.org/libsodium/releases/old
+$(package)_download_path=https://download.libsodium.org/libsodium/releases/old/unsupported
```

**Comment by cipig** [comment]
komodod builds fine with libsodium 1.0.18
https://github.com/KomodoPlatform/komodo/commit/5bb0bdffac7331e41baa40b563d342071df69110

**Comment by leto** [comment]
@cipig that is really good to know, but it seems like we should put a libsodium version upgrade thru more testing. I agree that we want to update to 1.0.18 long term. I made this PR before I saw this comment:

https://github.com/jl777/komodo/pull/1763

@jl777 do you have a preference?

**Comment by leto** [comment]
After looking at the release notes, it looks low-risk to upgrade and there seems to be many performance improvements. I have upgraded to 1.0.18 on the `duke` branch. Thanks again @cipig
