### ISSUE TITLE
Fix coinsupply RPC issues

### ISSUE THREAD

**Issue by leto** [MyHush/hush3#81]
Pirate has some nice new data in their `coinsupply`:

https://explorer.pirate.black/api/coinsupply

**Comment by DenioD** [comment]
These stats are allready in our Code. The problem is atm, that our Blockheight confuse the rpc. Mostly because our supply and blockheight doesnt match, because of the 500.000 Blocks before we hardfork to KMD codebase.

**Comment by leto** [comment]
@DenioD thanks for this clue, that helps. Marking this as a bug now

**Comment by leto** [comment]
The issue is that `coinsupply` looks for at least 1 year worth of blocks if it will return additional data, and we don't have that on our new mainnet yet. Problem will fix itself in April :smiley_cat:
