### ISSUE TITLE
ThreadNotifyWallets upstream bug

### ISSUE THREAD

**Issue by leto** [MyHush/hush3#87]
Research if this upstream bug affects us:

https://github.com/zcash/zcash/pull/4379

https://github.com/zcash/zcash/issues/4301

**Comment by daira** [comment]
This was introduced in https://github.com/zcash/zcash/pull/4252. We do recommend that you take that PR of you haven't already done so, as well as the fix in https://github.com/zcash/zcash/pull/4379.

**Comment by leto** [comment]
@DenioD do you have all your latest code on Github? I have some time to help you with this now, we should try to get this into the 3.3.2 release if we can

**Comment by zancas** [comment]
@leto note that #4379 introduced a race condition that is fixed in #4390 according to the associated commit messages.

**Comment by leto** [comment]
We have merged this code into our `dev` branch and made a new issue to track zcash#4390, thanks to @zancas for the heads up :+1:
